// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"net/http"
)

// Injectors from wire.go:

func InitializeServer() (*http.Server, func(), error) {
	logger := NewLogger()
	db, cleanup, err := ProvideDB(logger)
	if err != nil {
		return nil, nil, err
	}
	iPurchaseRepository := NewPurchaseRepository(db)
	iRequestGateway := NewRequestGateway()
	purchaseTransactionUsecase := NewTransactionUsecase(iPurchaseRepository, iRequestGateway)
	engine := NewRouter(purchaseTransactionUsecase, logger)
	string2 := ProvidePort()
	server := NewHTTPServer(engine, string2)
	return server, func() {
		cleanup()
	}, nil
}
